# App Engine configuration (alternative to Cloud Run)
runtime: python311

env_variables:
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  GCP_LOCATION: us-central1

automatic_scaling:
  min_instances: 0
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 4  # Increased from 2GB to 4GB for HEARTS model (~500MB) + headroom

