# Cloud Build configuration for Google Cloud Run
steps:
  # Build the container image (without HEARTS for faster builds)
  # Set ENABLE_HEARTS=true in substitutions to enable HEARTS model
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'ENABLE_HEARTS=${_ENABLE_HEARTS}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bias-analysis-tool'
      - '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bias-analysis-tool']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bias-analysis-tool'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bias-analysis-tool'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'  # Increased from default 2Gi for HEARTS model (~500MB) + processing headroom
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_LOCATION=us-central1'

images:
  - 'gcr.io/$PROJECT_ID/bias-analysis-tool'

options:
  machineType: 'E2_HIGHCPU_8'
  # Increase timeout to 1 hour (default is 10 minutes)
  timeout: '3600s'

# Substitutions (default values)
substitutions:
  _ENABLE_HEARTS: 'true'  # HEARTS model enabled (includes transformers, torch, shap, lime)

